### ISSUE TITLE
Documentar README sobre ceremonias en scrum

### ISSUE THREAD

**Issue by andresito-luna** [andresito-luna/pricipiantes_A24#1]
Editar el documento Readme.md agregando el concepto de Ceremonias, utilizando el material de estúdio provisto en el aula vurtual sobre SCRUM.

**Comment by facuezequiel02** [comment]
Ceremonias...
![Captura de pantalla (10)](https://user-images.githubusercontent.com/106352335/173460729-636d3698-ca1e-4a41-ba21-8b90153a364f.png)
![Captura de pantalla (11)](https://user-images.githubusercontent.com/106352335/173460737-ac6cd8fe-f49d-4f8e-8f2e-a38ff560172a.png)
![Captura de pantalla (12)](https://user-images.githubusercontent.com/106352335/173460753-bd96e479-d6a7-4c7c-8138-033880fe4757.png)
![Captura de pantalla (13)](https://user-images.githubusercontent.com/106352335/173460759-bcd043fa-bcad-4edf-9de2-a241ac8c77b6.png)
![Captura de pantalla (14)](https://user-images.githubusercontent.com/106352335/173460762-360de604-5db8-41f1-aa2b-147be19dae84.png)
![Captura de pantalla (15)](https://user-images.githubusercontent.com/106352335/173460764-a049f7c9-bc65-4975-b89e-1b669e4935a8.png)
![Captura de pantalla (16)](https://user-images.githubusercontent.com/106352335/173460769-384ca0e2-4e5c-4309-a28d-3fb5a399033a.png)

**Comment by andresito-luna** [comment]
> Ceremonias... ![Captura de pantalla (10)](https://user-images.githubusercontent.com/106352335/173460729-636d3698-ca1e-4a41-ba21-8b90153a364f.png) ![Captura de pantalla (11)](https://user-images.githubusercontent.com/106352335/173460737-ac6cd8fe-f49d-4f8e-8f2e-a38ff560172a.png) ![Captura de pantalla (12)](https://user-images.githubusercontent.com/106352335/173460753-bd96e479-d6a7-4c7c-8138-033880fe4757.png) ![Captura de pantalla (13)](https://user-images.githubusercontent.com/106352335/173460759-bcd043fa-bcad-4edf-9de2-a241ac8c77b6.png) ![Captura de pantalla (14)](https://user-images.githubusercontent.com/106352335/173460762-360de604-5db8-41f1-aa2b-147be19dae84.png) ![Captura de pantalla (15)](https://user-images.githubusercontent.com/106352335/173460764-a049f7c9-bc65-4975-b89e-1b669e4935a8.png) ![Captura de pantalla (16)](https://user-images.githubusercontent.com/106352335/173460769-384ca0e2-4e5c-4309-a28d-3fb5a399033a.png)

Tenes que pasar esos conceptos al ConceptosScrum.md.
