### ISSUE TITLE
Documentar README sobre roles en scrum

### ISSUE THREAD

**Issue by andresito-luna** [andresito-luna/pricipiantes_A24#3]
Editar el documento Readme.md agregando el concepto de roles, utilizando el material de estúdio provisto en el aula vurtual sobre SCRUM.

**Comment by mastrangeloispc** [comment]
Hola. Estoy probando esto de los comentarios. Veo que asignaste a Tami, Vivian y a mi la tarea de roles en scrum. Espero que este sea el medio para comentar estas cosas... Pero bueno, estamos probando!

**Comment by mastrangeloispc** [comment]
Bueno... subi algo ahí. Por supuesto que si quieren cambiar, poner, quitar... Para eso estamos

**Comment by andresito-luna** [comment]
Roberto...perfecto todo. A mi me notifica por mail del msj, así que estamos bien comunicados.

**Comment by mastrangeloispc** [comment]
La información la saqué de "La Guía del Scrum". Un PDF que subieron. Acá el link de la versión en español:
https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-Spanish-Latin-South-American.pdf
